# Generated by Django 6.1.1 on 2026-09-30 11:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SellerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(help_text='Your Business or Brand Name', max_length=255)),
                ('website', models.URLField(blank=True, help_text='Company Website URL', max_length=500, null=True)),
                ('product_categories', models.CharField(blank=True, help_text='Primary product categories (e.g., Furniture, Lighting, Wall Art, Rugs)', max_length=500)),
                ('from_name', models.CharField(help_text='Sender name displayed in buyer pitch emails', max_length=150)),
                ('from_email', models.EmailField(help_text='Verified email address used for sending pitches', max_length=254)),
                ('postal_address', models.TextField(help_text='Physical postal address included in email footer for CAN-SPAM compliance')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='seller_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
