# Generated by Django 6.1.1 on 2026-09-30 11:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApiCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cache_key', models.CharField(db_index=True, max_length=255, unique=True)),
                ('provider', models.CharField(max_length=50)),
                ('response_data', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(db_index=True)),
            ],
            options={
                'verbose_name': 'API Cache',
                'verbose_name_plural': 'API Caches',
            },
        ),
        migrations.CreateModel(
            name='ApiUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(db_index=True, max_length=50)),
                ('date', models.DateField(db_index=True, default=django.utils.timezone.now)),
                ('calls_count', models.IntegerField(default=0)),
                ('credits_used', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'API Usage',
                'verbose_name_plural': 'API Usages',
                'unique_together': {('provider', 'date')},
            },
        ),
    ]
