# Generated by Django 6.1.1 on 2026-09-30 11:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=10)),
                ('city', models.CharField(max_length=150)),
                ('radius_km', models.IntegerField(default=50)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running Discovery Pipeline'), ('done', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('total_found', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='search_queries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Buyer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=100)),
                ('website', models.URLField(blank=True, max_length=500, null=True)),
                ('domain', models.CharField(blank=True, db_index=True, max_length=255)),
                ('email', models.EmailField(blank=True, db_index=True, max_length=254, null=True)),
                ('email_source', models.CharField(choices=[('map_data', 'Map Data (Geoapify/OSM)'), ('crawler', 'Website Contact Crawler'), ('hunter', 'Hunter.io API'), ('none', 'No Email Found')], default='none', max_length=30)),
                ('email_status', models.CharField(choices=[('unverified', 'Unverified'), ('valid', 'Valid / Verified'), ('risky', 'Risky / Catch-All'), ('invalid', 'Invalid / No MX')], default='unverified', max_length=20)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('city', models.CharField(blank=True, max_length=150, null=True)),
                ('state', models.CharField(blank=True, max_length=50, null=True)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lon', models.FloatField(blank=True, null=True)),
                ('source_api', models.CharField(default='geoapify', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buyers', to=settings.AUTH_USER_MODEL)),
                ('search_query', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buyers', to='buyers.searchquery')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
